package fuji.parser;

public enum TokenType {
    // Literals
    IDENTIFIER,
    INT_LITERAL, FLOAT_LITERAL, STRING_LITERAL,

    // Operators
    PLUS, MINUS, STAR, SLASH, PERCENT, CARET, IS,
    EQUALS, NOT_EQUALS, LESS_THAN, GREATER_THAN, LESS_THAN_OR_EQUALS, GREATER_THAN_OR_EQUALS,
    AS, UNION, INTERSECTION, AND, OR, NOT,

    VARARG,

    // Punctuation
    LEFT_PARENTHESIS, RIGHT_PARENTHESIS, LEFT_CURLY_BRACKET, RIGHT_CURLY_BRACKET, LEFT_SQUARE_BRACKET, RIGHT_SQUARE_BRACKET,
    COMMA, COLON, SEMICOLON, ARROW, DOT, ASSIGN,

    // Control flow
    CONST, LET,
    IF, ELSE,
    WHILE, DO,
    IN, FOR,
    OBJECT, MAP, INTERFACE,
    ENUM,
    STRUCT,
    RETURN,
    EXTENDS,
    BREAK, CONTINUE,

    END_OF_FILE
}
